services:
  - type: web
    name: bookstore-fullstack-1
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://Eniya:1605@cluster0.0reauxr.mongodb.net/bookstore?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: mysecretkey123
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production